name: sleep

on:
  workflow_call:
    inputs:
      TIME_TO_SLEEP:
        description: how long to sleep for
        type: string
        required: true
      ENVIRONMENT:
        description: what GitHub environment to run the job for
        type: string
        required: false
      SHOULD_FAIL:
        description: whether or not the workflow should fail at the end of the sleep
        type: boolean
        required: false
        default: false
      CONCURRENCY_KEY:
        description: ensure execution of only 1 of these jobs at time on this id
        type: string
        required: false

jobs:
  sleep:
    concurrency: ${{ inputs.CONCURRENCY_KEY }}
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '::info::sleeping for ${{ inputs.TIME_TO_SLEEP }}s...'
          sleep ${{ inputs.TIME_TO_SLEEP }}
          echo '::info::sleep over; finishing job'
      - if: ${{ inputs.SHOULD_FAIL == 'true' }}
        run:
          echo '::info::erroring workflow out as requested'
          exit 1
