name: sleep

on:
  workflow_call:
    inputs:
      TIME_TO_SLEEP:
        description: how long to sleep for
        type: string
        required: true
      ENVIRONMENT:
        description: what GitHub environment to run the job for
        type: string
        required: false

jobs:
  sleep:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '::info::sleeping for ${{ inputs.TIME_TO_SLEEP }}s...'
          sleep ${{ inputs.TIME_TO_SLEEP }}
          echo '::info::sleep over; finishing job'
